### LIKE A POST
POST http://127.0.0.1:8000/api/posts/1/like/
Authorization: Token {{<token>}}

### LIKE THE SAME POST AGAIN (should return already liked message)
POST http://127.0.0.1:8000/api/posts/1/like/
Authorization: Token {{<token>}}

### UNLIKE A POST
POST http://127.0.0.1:8000/api/posts/1/unlike/
Authorization: Token {{<token>}}

### UNLIKE AGAIN (should return not liked message)
POST http://127.0.0.1:8000/api/posts/1/unlike/
Authorization: Token {{<token>}}

### GET NOTIFICATIONS
GET http://127.0.0.1:8000/api/notifications/
Authorization: Token {{<token>}}

### MARK A NOTIFICATION AS READ
POST http://127.0.0.1:8000/api/notifications/1/read/
Authorization: Token {{<token>}}

### MARK ALL NOTIFICATIONS AS READ
POST http://127.0.0.1:8000/api/notifications/mark-all-read/
Authorization: Token {{<token>}}
